import type { DashboardClusterSnapshot } from "../src/lib/contracts";

/** Minimal two-group snapshot with one of every interesting shape. */
export const snapshot: DashboardClusterSnapshot = {
  schemaVersion: 4,
  generatedAt: "2026-07-27T12:00:00.000Z",
  summary: {
    enabledGroups: 2,
    activeInstances: 4,
    runningInstances: 3,
    warmInstances: 1,
    pendingWarmInstances: 1,
    reservedInstances: 2,
    playersOnline: 15,
    activeSessions: 2,
    queuedParties: 2,
    queuedPlayers: 3,
    activeIncidentCount: 0,
    criticalIncidentCount: 0,
  },
  hosts: [
    {
      id: "host-paris-01",
      controlUrl: "http://host-paris-01:8090",
      gameAddress: "10.20.0.11",
      healthState: "ONLINE",
      adminState: "ACTIVE",
      allocatableCpu: 16,
      reservedCpu: 8,
      allocatableMemoryBytes: 32 * 1024 ** 3,
      reservedMemoryBytes: 12 * 1024 ** 3,
      activeInstanceCount: 2,
      agentVersion: "0.1.0",
      lastHeartbeatAt: "2026-07-27T11:59:58.000Z",
      lastControlContactAt: "2026-07-27T11:59:57.000Z",
      lastError: null,
    },
    {
      id: "host-paris-02",
      controlUrl: "http://host-paris-02:8090",
      gameAddress: "10.20.0.12",
      healthState: "ONLINE",
      adminState: "ACTIVE",
      allocatableCpu: 16,
      reservedCpu: 8,
      allocatableMemoryBytes: 32 * 1024 ** 3,
      reservedMemoryBytes: 12 * 1024 ** 3,
      activeInstanceCount: 2,
      agentVersion: "0.1.0",
      lastHeartbeatAt: "2026-07-27T11:59:58.000Z",
      lastControlContactAt: "2026-07-27T11:59:57.000Z",
      lastError: null,
    },
  ],
  groups: [
    {
      id: "hub",
      type: "hub",
      enabled: true,
      capacity: {
        minimumInstances: 1,
        maximumInstances: 4,
        minimumWarmInstances: 1,
        maximumWarmInstances: 2,
        activeInstances: 1,
        warmInstances: 1,
        pendingWarmInstances: 0,
        reservedInstances: 0,
      },
      timeouts: {
        startupMs: 90_000,
        drainMs: 900_000,
        cancelledDrainMs: 10_000,
        shutdownMs: 20_000,
        transferMs: 20_000,
        playerStaleMs: 30_000,
        instanceLifetimeMs: 14_400_000,
        instanceAcquisitionMs: null,
        lobbyStaleMs: null,
      },
      matchmaking: null,
      routing: { maximumPlayersPerInstance: 100, targetPlayersPerInstance: 60 },
      queue: { partyCount: 0, playerCount: 0, oldestJoinedAt: null },
      variants: [
        {
          id: "hub-aurora",
          enabled: true,
          revision: 1,
          weight: 100,
          runtime: {
            image: "itzg/minecraft-server:java25",
            memoryBytes: 6 * 1024 ** 3,
            cpu: 4,
            environment: {},
          },
        },
      ],
      instances: [
        {
          id: "hubinstance00001",
          hostId: "host-paris-01",
          variantId: "hub-aurora",
          sessionId: null,
          lifecycleState: "RUNNING",
          availabilityState: "OPEN",
          endpoint: "ec-hub-aurora-1:25565",
          playerCount: 7,
          maximumPlayers: 100,
          createdAt: "2026-07-27T11:00:00.000Z",
          startingAt: "2026-07-27T11:00:10.000Z",
          startupDeadline: null,
          runningAt: "2026-07-27T11:00:40.000Z",
          renewalDeadline: "2026-07-27T15:00:40.000Z",
          replacesInstanceId: null,
          drainingAt: null,
          drainDeadline: null,
          drainReason: null,
          stoppingAt: null,
          shutdownDeadline: null,
          updatedAt: "2026-07-27T11:59:55.000Z",
        },
      ],
      sessions: [],
    },
    {
      id: "skywars-solo",
      type: "minigame",
      enabled: true,
      capacity: {
        minimumInstances: 0,
        maximumInstances: 20,
        minimumWarmInstances: 2,
        maximumWarmInstances: 4,
        activeInstances: 3,
        warmInstances: 0,
        pendingWarmInstances: 1,
        reservedInstances: 2,
      },
      timeouts: {
        startupMs: 90_000,
        drainMs: 900_000,
        cancelledDrainMs: 10_000,
        shutdownMs: 20_000,
        transferMs: 20_000,
        playerStaleMs: 30_000,
        instanceLifetimeMs: null,
        instanceAcquisitionMs: 45_000,
        lobbyStaleMs: 135_000,
      },
      matchmaking: {
        minimumPlayers: 4,
        maximumPlayers: 12,
        teamCount: 12,
        teamSize: 1,
        candidateWindow: 20,
        minimumPlayersPerTeam: 0,
        maximumTeamSpread: 1,
      },
      routing: null,
      queue: {
        partyCount: 2,
        playerCount: 3,
        oldestJoinedAt: "2026-07-27T11:59:30.000Z",
      },
      variants: [
        {
          id: "skywars-japan",
          enabled: true,
          revision: 2,
          weight: 100,
          runtime: {
            image: "itzg/minecraft-server:java25",
            memoryBytes: 4 * 1024 ** 3,
            cpu: 2,
            environment: {},
          },
        },
      ],
      instances: [
        {
          id: "skywarsrunning01",
          hostId: "host-paris-01",
          variantId: "skywars-japan",
          sessionId: "skywarssession01",
          lifecycleState: "RUNNING",
          availabilityState: "RESERVED",
          endpoint: "ec-skywars-japan-1:25566",
          playerCount: 8,
          maximumPlayers: 12,
          createdAt: "2026-07-27T11:55:00.000Z",
          startingAt: "2026-07-27T11:55:05.000Z",
          startupDeadline: null,
          runningAt: "2026-07-27T11:55:30.000Z",
          renewalDeadline: null,
          replacesInstanceId: null,
          drainingAt: null,
          drainDeadline: null,
          drainReason: null,
          stoppingAt: null,
          shutdownDeadline: null,
          updatedAt: "2026-07-27T11:59:58.000Z",
        },
        {
          id: "skywarsfailed001",
          hostId: "host-paris-02",
          variantId: "skywars-japan",
          sessionId: null,
          lifecycleState: "FAILED",
          availabilityState: "OPEN",
          endpoint: null,
          playerCount: 0,
          maximumPlayers: 12,
          createdAt: "2026-07-27T11:50:00.000Z",
          startingAt: "2026-07-27T11:50:05.000Z",
          startupDeadline: "2026-07-27T11:51:35.000Z",
          runningAt: null,
          renewalDeadline: null,
          replacesInstanceId: null,
          drainingAt: null,
          drainDeadline: null,
          drainReason: null,
          stoppingAt: null,
          shutdownDeadline: null,
          updatedAt: "2026-07-27T11:51:00.000Z",
        },
        {
          id: "skywarscreating1",
          hostId: "host-paris-02",
          variantId: "skywars-japan",
          sessionId: null,
          lifecycleState: "CREATING",
          availabilityState: "OPEN",
          endpoint: null,
          playerCount: 0,
          maximumPlayers: 12,
          createdAt: "2026-07-27T11:59:50.000Z",
          startingAt: null,
          startupDeadline: null,
          runningAt: null,
          renewalDeadline: null,
          replacesInstanceId: null,
          drainingAt: null,
          drainDeadline: null,
          drainReason: null,
          stoppingAt: null,
          shutdownDeadline: null,
          updatedAt: "2026-07-27T11:59:50.000Z",
        },
      ],
      sessions: [
        {
          id: "skywarssession01",
          instanceId: "skywarsrunning01",
          state: "RUNNING",
          assignmentRevision: 1,
          assignmentAcknowledgedAt: "2026-07-27T11:55:40.000Z",
          instanceAcquisitionDeadline: null,
          lobbyStaleDeadline: "2026-07-27T11:58:15.000Z",
          retryCount: 0,
          maximumPlayerCount: 12,
          activePlayerCount: 8,
          connectedPlayerCount: 8,
          teamCount: 8,
          createdAt: "2026-07-27T11:55:00.000Z",
          startedAt: "2026-07-27T11:55:45.000Z",
          finishedAt: null,
          updatedAt: "2026-07-27T11:59:58.000Z",
        },
        {
          id: "skywarssession02",
          instanceId: null,
          state: "WAITING_FOR_INSTANCE",
          assignmentRevision: 0,
          assignmentAcknowledgedAt: null,
          instanceAcquisitionDeadline: "2026-07-27T12:00:30.000Z",
          lobbyStaleDeadline: null,
          retryCount: 1,
          maximumPlayerCount: 12,
          activePlayerCount: 6,
          connectedPlayerCount: 0,
          teamCount: 6,
          createdAt: "2026-07-27T11:59:45.000Z",
          startedAt: null,
          finishedAt: null,
          updatedAt: "2026-07-27T11:59:59.000Z",
        },
      ],
    },
  ],
};
