import type { DashboardClusterSnapshot } from "../src/lib/contracts";

/** Minimal two-group snapshot with one of every interesting shape. */
export const snapshot: DashboardClusterSnapshot = {
  schemaVersion: 1,
  generatedAt: "2026-07-27T12:00:00.000Z",
  summary: {
    enabledGroups: 2,
    activeInstances: 4,
    runningInstances: 3,
    warmInstances: 1,
    pendingWarmInstances: 1,
    reservedInstances: 2,
    playersOnline: 15,
    activeSessions: 2,
    queuedParties: 2,
    queuedPlayers: 3,
  },
  groups: [
    {
      id: "hub",
      type: "hub",
      enabled: true,
      capacity: {
        minimumInstances: 1,
        maximumInstances: 4,
        minimumWarmInstances: 1,
        maximumWarmInstances: 2,
        activeInstances: 1,
        warmInstances: 1,
        pendingWarmInstances: 0,
        reservedInstances: 0,
      },
      lifecycle: {
        startupTimeoutMs: 90_000,
        drainingTimeoutMs: 900_000,
        shutdownTimeoutMs: 20_000,
      },
      matchmaking: null,
      routing: { maximumPlayersPerInstance: 100, targetPlayersPerInstance: 60 },
      queue: { partyCount: 0, playerCount: 0, oldestJoinedAt: null },
      variants: [
        {
          id: "hub-aurora",
          enabled: true,
          revision: 1,
          weight: 100,
          runtime: {
            image: "itzg/minecraft-server:java25",
            memoryBytes: 6 * 1024 ** 3,
            cpu: 4,
            environment: {},
          },
        },
      ],
      instances: [
        {
          id: "hubinstance00001",
          variantId: "hub-aurora",
          sessionId: null,
          lifecycleState: "RUNNING",
          availabilityState: "OPEN",
          endpoint: "ec-hub-aurora-1:25565",
          playerCount: 7,
          maximumPlayers: 100,
          createdAt: "2026-07-27T11:00:00.000Z",
          startingAt: "2026-07-27T11:00:10.000Z",
          runningAt: "2026-07-27T11:00:40.000Z",
          drainingAt: null,
          drainDeadline: null,
          updatedAt: "2026-07-27T11:59:55.000Z",
        },
      ],
      sessions: [],
    },
    {
      id: "skywars-solo",
      type: "minigame",
      enabled: true,
      capacity: {
        minimumInstances: 0,
        maximumInstances: 20,
        minimumWarmInstances: 2,
        maximumWarmInstances: 4,
        activeInstances: 3,
        warmInstances: 0,
        pendingWarmInstances: 1,
        reservedInstances: 2,
      },
      lifecycle: {
        startupTimeoutMs: 90_000,
        drainingTimeoutMs: 900_000,
        shutdownTimeoutMs: 20_000,
      },
      matchmaking: {
        minimumPlayers: 4,
        maximumPlayers: 12,
        teamCount: 12,
        teamSize: 1,
        waitingTimeoutMs: 45_000,
        candidateWindow: 20,
        instanceWaitTimeoutMs: 45_000,
        maximumWaitingTimeoutMs: 135_000,
        minimumPlayersPerTeam: 0,
        maximumTeamSpread: 1,
      },
      routing: null,
      queue: {
        partyCount: 2,
        playerCount: 3,
        oldestJoinedAt: "2026-07-27T11:59:30.000Z",
      },
      variants: [
        {
          id: "skywars-japan",
          enabled: true,
          revision: 2,
          weight: 100,
          runtime: {
            image: "itzg/minecraft-server:java25",
            memoryBytes: 4 * 1024 ** 3,
            cpu: 2,
            environment: {},
          },
        },
      ],
      instances: [
        {
          id: "skywarsrunning01",
          variantId: "skywars-japan",
          sessionId: "skywarssession01",
          lifecycleState: "RUNNING",
          availabilityState: "RESERVED",
          endpoint: "ec-skywars-japan-1:25566",
          playerCount: 8,
          maximumPlayers: 12,
          createdAt: "2026-07-27T11:55:00.000Z",
          startingAt: "2026-07-27T11:55:05.000Z",
          runningAt: "2026-07-27T11:55:30.000Z",
          drainingAt: null,
          drainDeadline: null,
          updatedAt: "2026-07-27T11:59:58.000Z",
        },
        {
          id: "skywarsfailed001",
          variantId: "skywars-japan",
          sessionId: null,
          lifecycleState: "FAILED",
          availabilityState: "OPEN",
          endpoint: null,
          playerCount: 0,
          maximumPlayers: 12,
          createdAt: "2026-07-27T11:50:00.000Z",
          startingAt: "2026-07-27T11:50:05.000Z",
          runningAt: null,
          drainingAt: null,
          drainDeadline: null,
          updatedAt: "2026-07-27T11:51:00.000Z",
        },
        {
          id: "skywarscreating1",
          variantId: "skywars-japan",
          sessionId: null,
          lifecycleState: "CREATING",
          availabilityState: "OPEN",
          endpoint: null,
          playerCount: 0,
          maximumPlayers: 12,
          createdAt: "2026-07-27T11:59:50.000Z",
          startingAt: null,
          runningAt: null,
          drainingAt: null,
          drainDeadline: null,
          updatedAt: "2026-07-27T11:59:50.000Z",
        },
      ],
      sessions: [
        {
          id: "skywarssession01",
          instanceId: "skywarsrunning01",
          state: "RUNNING",
          assignmentRevision: 1,
          assignmentAcknowledgedAt: "2026-07-27T11:55:40.000Z",
          waitingDeadline: "2026-07-27T11:56:15.000Z",
          maximumWaitingDeadline: "2026-07-27T11:58:15.000Z",
          retryCount: 0,
          maximumPlayerCount: 12,
          activePlayerCount: 8,
          connectedPlayerCount: 8,
          teamCount: 8,
          createdAt: "2026-07-27T11:55:00.000Z",
          startedAt: "2026-07-27T11:55:45.000Z",
          finishedAt: null,
          updatedAt: "2026-07-27T11:59:58.000Z",
        },
        {
          id: "skywarssession02",
          instanceId: null,
          state: "WAITING_FOR_INSTANCE",
          assignmentRevision: 0,
          assignmentAcknowledgedAt: null,
          waitingDeadline: "2026-07-27T12:00:30.000Z",
          maximumWaitingDeadline: null,
          retryCount: 1,
          maximumPlayerCount: 12,
          activePlayerCount: 6,
          connectedPlayerCount: 0,
          teamCount: 6,
          createdAt: "2026-07-27T11:59:45.000Z",
          startedAt: null,
          finishedAt: null,
          updatedAt: "2026-07-27T11:59:59.000Z",
        },
      ],
    },
  ],
};
